= Scripts and Binding

Geb supports being used in scripting environments via both the `Browser.drive()` method, and by using the link:api/geb/binding/BindingUpdater.html[`geb.binding.BindingUpdater`] class that populates and updates a http://groovy.codehaus.org/api/groovy/lang/Binding.html[`groovy.lang.Binding`] that can be used with scripts. This is also the same mechanism that is used by the link:testing/#easyb[EasyB Geb plugin] and can be used with link:testing/#cucumber_cuke4duke[Cuke4Duke] (Cucumber for the JVM).

== Setup

To use the binding support, you simply create a link:api/geb/binding/BindingUpdater.html[`BindingUpdater`] object with a http://groovy.codehaus.org/api/groovy/lang/Binding.html[`Binding`] and link:api/geb/Browser.html[`Browser`]...

[source,groovy]
----
import geb.Browser
import geb.binding.BindingUpdater
import groovy.lang.Binding

def binding = new Binding()
def browser = new Browser()
def updater = new BindingUpdater(binding, browser)

// populate and start updating the browser
updater.initialize()

// Run a script from the filesystem
new GroovyShell(binding).evaluate(new File("someScript.groovy"))

// remove Geb bits from the binding and stop updating it
updater.remove()
----
    
== The binding environment

=== Browser methods & properties

The link:api/geb/binding/BindingUpdater.html[`BindingUpdater`] installs shortcuts into the binding for most of the link:api/geb/Browser.html[browser] object's public methods. 

For example...

[source,groovy]
----
go "some/page"
assert at(SomePage)
waitFor { $("p.status").text() == "ready" }
js.someJavaScriptFunction()
downloadText($("a.csvFile"))
----

In a managed binding, all of the methods/properties that you can usually call in the link:binding/#the_drive_method[`Browser.drive()`] method are available. This includes the `$()` function.

The following methods are available:

* $
* go
* to
* at
* waitFor
* withAlert
* withNoAlert
* withConfirm
* withNoConfirm
* download
* downloadStream
* downloadText
* downloadBytes
* downloadContent
* report
* reportGroup
* cleanReportGroupDir

The javascript interface property link:javascript/#the_js_object[`js`] is also available. The browser object itself is available as the `browser` property.

=== The current page

The binding updater also updates the `page` property of the binding to be the browser's current page...

[source,groovy]
----
import geb.Page

class SomePage extends Page {
    static content = {
        button(to: OtherPage) { $("input.do-stuff") }
    }
}

to SomePage
assert page instanceof SomePage
page.button.click()
assert page instanceof OtherPage
----